# module: users.conf — renamed default account fields for Crude OS
defaultGroups:
    - users
    - wheel
    - audio
    - video
    - storage
    - lp
    - netdev

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true

userShell: /bin/bash

# Suggests a friendlier default hostname than plain "alpine"
hostname: crudeos-pc
